name: whats_happening
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: 1.20.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  bloc:
  flutter_bloc:
  equatable:
  dio:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter:

flutter:

  uses-material-design: true

  assets:
  - secret_config.json

import_sorter:
  comments: false